# Generated by Django 3.1 on 2021-05-16 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CreateAccount', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='activeReceived',
        ),
        migrations.RemoveField(
            model_name='account',
            name='activeSent',
        ),
        migrations.RemoveField(
            model_name='account',
            name='documentsReceived',
        ),
        migrations.RemoveField(
            model_name='account',
            name='receivedDocumentIDs',
        ),
    ]
