# Generated by Django 3.1 on 2021-05-17 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ManageDocument', '0002_auto_20210517_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='fingerprintsPerAction',
        ),
    ]
