# Generated by Django 3.1 on 2021-05-17 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ManageDocument', '0003_remove_document_fingerprintsperaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='actionAtIPList',
        ),
        migrations.RemoveField(
            model_name='document',
            name='associatedWith',
        ),
        migrations.RemoveField(
            model_name='document',
            name='dateCreatedBy',
        ),
        migrations.RemoveField(
            model_name='document',
            name='dateLastEdited',
        ),
        migrations.RemoveField(
            model_name='document',
            name='documentProcess',
        ),
        migrations.RemoveField(
            model_name='document',
            name='timeAddedTo',
        ),
        migrations.RemoveField(
            model_name='document',
            name='timeSignedBy',
        ),
        migrations.RemoveField(
            model_name='document',
            name='timeViewedBy',
        ),
    ]
