# Generated by Django 3.1 on 2021-05-17 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManageDocument', '0004_auto_20210517_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document',
            field=models.FileField(default='default', upload_to='documents/'),
            preserve_default=False,
        ),
    ]
