# Generated by Django 3.1 on 2021-05-18 00:17

import ManageDocument.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManageDocument', '0005_document_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to=ManageDocument.models.path_and_rename),
        ),
    ]
